### ISSUE TITLE
Can't use Http fake when testing requests

### ISSUE THREAD

**Issue by markwalet** [saloonphp/laravel-http-sender#13]
I'm trying to test my code with the `Http::fake()` method. I'm expecting this to work with the http-sender plugin.

```php
/** @test */
public function it_can_configure_the_base_url(): void
{
    Http::fake(function (Request $request) {
        dd($request);
    });

    /** @var MCOConnector $connector */
    $connector = $this->app->make(TestConnector::class);

    $request = $connector->send(new TestRequest());
}
```

I know there are some other ways to test the requests, but I like the freedom you get with the `Http::fake()` callback. Even if this becomes possible with Saloon, I'm still questioning why this isn't working in the first place.

Keep up the good work, I'm loving the package and ecosystem!

**Comment by markwalet** [comment]
That's a possibility. I'm not really familiar with the package yet so this is hard to debug. 

Can you confirm that the snippet I provided is a bug? Maybe I'm just using it wrong.

**Comment by Sammyjo20** [comment]
Looks like #15 might have you covered! 🔥

**Comment by Sammyjo20** [comment]
Going to close this issue as I think Saloon's faking helpers are okay for now.
