### ISSUE TITLE
Telescope does not record the HTTP requests send by Saloon

### ISSUE THREAD

**Issue by jeffrey-kroonen** [saloonphp/laravel-http-sender#16]
Hi, thank you for building the most robust HTTP API integration package out there! I really appreciate your work.

Recently I've installed the `laravel-http-sender` package and configured the `config/saloon.php` to make use of the class `Saloon\HttpSender\HttpSender` as `default_sender`.

When I send a request with Saloon, it will not be recorded in Telescope.

Is their something I must configure at the Telescope side?

**Telescope**

- The `config/telescope.php` has not been altered after publishing.
- The TelescopeServiceProvider has not been altered

If you need more information, please let me know (:

**Comment by Sammyjo20** [comment]
Hey @jeffrey-kroonen thank you so much for the kind words! That’s strange - have you checked under the “HTTP Requests/Client” section in telescope? That’s where you’ll find it. 

if you could please confirm the Laravel version you’re using and Saloon versions that’ll be great. 

Also, are you able to dump the $this->sender() inside of your connector’s instructor just to confirm that it’s definitely the HttpSender?

**Comment by jeffrey-kroonen** [comment]
Hi @Sammyjo20 ,

Thank for your fast reply. I've tried it again this morning and it was because of the `dd()` use the sql-transaction couldn't be finished. So after removing the `dd()`, the entry was created in telescope 🎉

Sorry for wasting your time..

Have a nice day!

**Comment by Sammyjo20** [comment]
All good - have a good one!
